# Global settings
nameOverride: ""
fullnameOverride: ""
  

# Frontend service
frontend:
  enabled: true
  replicaCount: 1
  image:
    repository: forensicxlab/volweb-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Backend service
backend:
  enabled: true
  replicaCount: 1
  image:
    repository: forensicxlab/volweb-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    DATABASE: "postgres"
    DATABASE_HOST: "volweb-postgresdb"
    CSRF_TRUSTED_ORIGINS: "https://10.113.80.205.nip.io:3000"
    DATABASE_PORT: "5432"
    POSTGRES_USER: "volweb"
    POSTGRES_PASSWORD: "volweb"
    POSTGRES_DB: "volweb"
    DJANGO_SECRET: "change_me_or_die"
    BROKER_HOST: "volweb-redis"
    BROKER_PORT: "6379"
  persistence:
    enabled: true
    storageClass: "standard"
    size: 1Gi

# Workers service (Celery)
workers:
  enabled: true
  replicaCount: 2
  image:
    repository: forensicxlab/volweb-backend
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 2Gi
    requests:
      cpu: 200m
      memory: 1Gi
  env:
    DATABASE: "postgres"
    DATABASE_HOST: "volweb-postgresdb"
    CSRF_TRUSTED_ORIGINS: "https://10.113.80.205.nip.io:3000"
    DATABASE_PORT: "5432"
    POSTGRES_USER: "volweb"
    POSTGRES_PASSWORD: "volweb"
    POSTGRES_DB: "volweb"
    DJANGO_SECRET: "change_me_or_die"
    BROKER_HOST: "volweb-redis"
    BROKER_PORT: "6379"
  persistence:
    enabled: true
    storageClass: "standard"
    size: 1Gi

# Database (PostgreSQL)
postgresdb:
  enabled: true
  image:
    repository: postgres
    tag: 14.1
    pullPolicy: IfNotPresent
  service:
    port: 5432
  persistence:
    enabled: true
    storageClass: "standard"
    size: 1Gi
  env:
    POSTGRES_USER: "volweb"
    POSTGRES_PASSWORD: "volweb"
    POSTGRES_DB: "volweb"

# Redis
redis:
  enabled: true
  image:
    repository: redis
    tag: 6
    pullPolicy: IfNotPresent
  service:
    port: 6379
  persistence:
    enabled: true
    storageClass: "standard"
    size: 1Gi
    mountPath: /data

# Nginx for routing/proxy
nginx:
  enabled: true
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 443
  config:
    clientMaxBodySize: "100M"

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  hosts:
    - host: 10.113.80.205.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: volweb-tls
      hosts:
        - 10.113.80.205.nip.io
