# Global settings
nameOverride: ""
fullnameOverride: ""

# Frontend service
frontend:
  enabled: true
  replicaCount: 1
  image:
    repository: forensicxlab/volweb-frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  env:
    NODE_ENV: production

# Backend service
backend:
  enabled: true
  replicaCount: 1
  image:
    repository: forensicxlab/volweb-backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    DEBUG: "False"
    SECRET_KEY: "change-me-in-production"
    ALLOWED_HOSTS: "*"
    CSRF_TRUSTED_ORIGINS: "https://yourdomain.com:3000"
    DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"
    REDIS_URL: "redis://redis:6379/0"
  persistence:
    enabled: true
    storageClass: ""
    size: 100Gi
    mountPath: /app/media

# Workers service (Celery)
workers:
  enabled: true
  replicaCount: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  env:
    DEBUG: "False"
  persistence:
    enabled: true
    storageClass: ""
    size: 100Gi
    mountPath: /app/media


# Database (PostgreSQL)
postgresdb:
  enabled: true
  image:
    repository: postgres
    tag: 14.1
    pullPolicy: IfNotPresent
  service:
    port: 5432
  persistence:
    enabled: true
    size: 5Gi
  env:
    POSTGRES_PASSWORD: "postgres"
    POSTGRES_USER: "postgres"
    POSTGRES_DB: "postgres"

# Redis
redis:
  enabled: true
  image:
    repository: redis
    tag: 6
    pullPolicy: IfNotPresent
  service:
    port: 6379
  persistence:
    enabled: true
    size: 1Gi

# Nginx for routing/proxy
nginx:
  enabled: true
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 443
  config:
    clientMaxBodySize: "100M"

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  hosts:
    - host: volweb.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: volweb-tls
      hosts:
        - volweb.example.com
