{{- if .Values.backend.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "volweb.fullname" . }}-backend-media
  labels:
    {{- include "volweb.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.backend.persistence.storageClass }}
  storageClassName: {{ .Values.backend.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
{{- end }}


{{- if .Values.postgresdb.persistence.enabled -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "volweb.fullname" . }}-postgresdb-data
  labels:
    {{- include "volweb.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgresdb.persistence.storageClass }}
  storageClassName: {{ .Values.postgresdb.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresdb.persistence.size }}
{{- end }}


{{- if .Values.redis.persistence.enabled -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "volweb.fullname" . }}-redis-data
  labels:
    {{- include "volweb.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.redis.persistence.storageClass }}
  storageClassName: {{ .Values.redis.persistence.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size }}
{{- end }}
