{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "volweb.fullname" . }}-nginx-config
  labels:
    {{- include "volweb.labels" . | nindent 4 }}
data:
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    
    events {
        worker_connections  1024;
    }
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        
        access_log  /var/log/nginx/access.log  main;
        
        sendfile        on;
        keepalive_timeout  65;
        
        client_max_body_size {{ .Values.nginx.config.clientMaxBodySize }};
        
        server {
            listen 80;
            server_name _;
            
            location /api/ {
                proxy_pass http://{{ include "volweb.fullname" . }}-backend:{{ .Values.backend.service.port }}/api/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /admin/ {
                proxy_pass http://{{ include "volweb.fullname" . }}-backend:{{ .Values.backend.service.port }}/admin/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /media/ {
                proxy_pass http://{{ include "volweb.fullname" . }}-backend:{{ .Values.backend.service.port }}/media/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            
            location /static/ {
                proxy_pass http://{{ include "volweb.fullname" . }}-backend:{{ .Values.backend.service.port }}/static/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
            }
            
            location / {
                proxy_pass http://{{ include "volweb.fullname" . }}-frontend:{{ .Values.frontend.service.port }}/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
{{- end }}
