{{- if .Values.frontend.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "volweb.fullname" . }}-frontend
  labels:
    {{- include "volweb.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "volweb.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "volweb.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            {{- range $key, $value := .Values.frontend.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          {{- if .Values.backend.persistence.enabled }}
          volumeMounts:
            - name: staticfiles
              mountPath: /home/app/web/staticfiles
            - name: media
              mountPath: /home/app/web/media
          {{- end }}
      {{- if .Values.backend.persistence.enabled }}
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: {{ include "volweb.fullname" . }}-staticfiles
        - name: media
          persistentVolumeClaim:
            claimName: {{ include "volweb.fullname" . }}-media
      {{- end }}
{{- end }}
