{{- if .Values.postgresdb.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "volweb.fullname" . }}-postgresdb
  labels:
    {{- include "volweb.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "volweb.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgresdb
  template:
    metadata:
      labels:
        {{- include "volweb.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgresdb
    spec:
      containers:
        - name: postgresdb
          image: "{{ .Values.postgresdb.image.repository }}:{{ .Values.postgresdb.image.tag }}"
          imagePullPolicy: {{ .Values.postgresdb.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            {{- range $key, $value := .Values.postgresdb.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- if .Values.postgresdb.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          {{- end }}
      {{- if .Values.postgresdb.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "volweb.fullname" . }}-postgresdb-data
      {{- end }}
{{- end }}
