{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "volweb.fullname" . }}-postgresql
  labels:
    {{- include "volweb.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "volweb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
